---
# tasks file for ansible-role-packer

- name: Include OS specific variables.
  include_vars: "{{ ansible_system }}.yml"

- name: Linux/Unix | Install Packer
  include_tasks: "setup-Linux-Unix.yml"
  when: ansible_system != "Win32NT"

- name: Windows | Install Packer
  include_tasks: "setup-Windows.yml"
  when: ansible_system == "Win32NT"
