---
- name: Verify
  hosts: all
  tasks:
  - name: OpenBSD | Packer should be functionnal
    command: packer --version
    ignore_errors: yes
    register: packer_result

  - name: OpenBSD | Verify commands outputs
    assert:
      that:
        - packer_result.rc == 0
      success_msg: "All tests passed"
