---
- name: Verify
  hosts: all
  tasks:
  - name: Linux | Packer should be functionnal
    command: packer --version
    register: packer_result

  - name: Linux | Verify commands outputs
    assert:
      that:
        - packer_result.rc == 0
      success_msg: "All tests passed"
    when: ansible_env.packer_version == "latest"

  - name: Linux | Verify commands outputs
    assert:
      that:
        - packer_result.rc == 0
        - ansible_env.packer_version in packer_result.stdout
      success_msg: "All tests passed"
    when: ansible_env.packer_version != "latest"
