---
- name: Verify
  hosts: all
  tasks:
    - name: FreeBSD | Packer should be functionnal
      ansible.builtin.command: packer --version
      register: packer_result

    - name: FreeBSD | Verify commands outputs
      ansible.builtin.assert:
        that:
          - packer_result.rc == 0
        success_msg: "All tests passed"
      when: lookup('env', 'packer_version') == "latest"

    - name: FreeBSD | Verify commands outputs
      ansible.builtin.assert:
        that:
          - packer_result.rc == 0
          - lookup('env', 'packer_version') in packer_result.stdout
        success_msg: "All tests passed"
      when: lookup('env', 'packer_version') != "latest"
